apiVersion: v1
kind: Service
metadata:
  name: chat-mengxin-ml-clusterip
  namespace: web
  labels:
    app: chat-mengxin-ml
spec:
  selector:
    pod: chat-mengxin-ml
  type: ClusterIP
  ports:
    - name: chat-http
      port: 3000
      targetPort: 3000
