apiVersion: v1
kind: Service
metadata:
  name: httpbin-mengxin-ml-clusterip
  namespace: web
spec:
  selector:
    pod: httpbin-mengxin-ml
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80