apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-tunnel-tunnel-mengxin-ml-deployment
  namespace: web
  labels:
    app: argo-tunnel-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: argo-tunnel-tunnel-mengxin-ml
  template:
    metadata:
      labels:
        pod: argo-tunnel-tunnel-mengxin-ml
    spec:
      containers:
        - name: argo-tunnel-tunnel-mengxin-ml
          image: cloudflare/cloudflared:2021.12.4
          volumeMounts:
          - name: argo-tunnel-tunnel-mengxin-ml-configmap-volume
            mountPath: /etc/cloudflared
          command: [ "cloudflared", "tunnel","--no-autoupdate","run","e6572126-7bb3-4f9b-84e6-076907a91854"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: argo-tunnel-tunnel-mengxin-ml-configmap-volume
          configMap:
            name: argo-tunnel-tunnel-mengxin-ml-configmap
      # restartPolicy: Never

