apiVersion: v1
kind: Service
metadata:
  name: redis-mengxin-ml-clusterip
  namespace: tcp
  labels:
    app: redis-mengxin-ml
spec:
  selector:
    pod: redis-mengxin-ml
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
