apiVersion: v1
kind: Service
metadata:
  name: sea-mengxin-ml-clusterip
spec:
  selector:
    app: sea-mengxin-ml-web
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
