apiVersion: v1
kind: Service
metadata:
  name: ssl-mengxin-ml-keyless-clusterip
  namespace: tcp
  labels:
    app: ssl-mengxin-ml-keyless
spec:
  selector:
    pod: ssl-mengxin-ml
  type: ClusterIP
  ports:
    - name: keyless
      port: 2407
      targetPort: 2407
    - name: metrics
      port: 2406
      targetPort: 2406
