apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-mengxin-ml-deployment
  namespace: web
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mongo-express-mengxin-ml
  template:
    metadata:
      labels:
        pod: mongo-express-mengxin-ml
    spec:
      containers:
        - name: mongo-mengxin-ml
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-express-mengxin-ml-config
                  key: ME_CONFIG_MONGODB_ADMINUSERNAME
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-express-mengxin-ml-config
                  key: ME_CONFIG_MONGODB_ADMINPASSWORD
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                secretKeyRef:
                  name: mongo-express-mengxin-ml-config
                  key: ME_CONFIG_MONGODB_SERVER
