apiVersion: v1
kind: Service
metadata:
  name: mongo-express-mengxin-ml-clusterip
  namespace: web
spec:
  selector:
    pod: mongo-express-mengxin-ml
  type: ClusterIP
  ports:
    - name: mongo-express
      port: 8081
      targetPort: 8081