
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-mengxin-ml-deployment
  namespace: tcp
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mongo-mengxin-ml
  template:
    metadata:
      labels:
        pod: mongo-mengxin-ml
    spec:
      # volumes:
        # - name: mongo-storage
        #   persistentVolumeClaim:
        #     claimName: mongo-storage-pvc
      volumes:
        - name: mongo-storage
          nfs:
            path: /mongo
            server: common-storage-nfs-clusterip.tcp.svc.cluster.local
      containers:
        - name: mongo-mengxin-ml
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-mengxin-ml-config
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-mengxin-ml-config
                  key: MONGO_ROOT_PASSWORD