apiVersion: v1
kind: Service
metadata:
  name: grpc-mengxin-ml-clusterip
  namespace: web
  labels:
    app: grpc-mengxin-ml
spec:
  selector:
    pod: grpc-mengxin-ml
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051